add visits add and get and its tests
ct-fiuba/visit-manager pull request #13
Opened 2020-11-01 15:48 UTC by tomasaccini

- Agregué las rutas POST /visits y GET /visits
- La ruta recibe scanCode, userGeneratedCode y timestamp
- Agregué tests unitarios y de integración

@ct-fiuba/developers

2020-11-02 16:18 UTC, NachoRaik requested changes
Re pio

2020-11-02 16:18 UTC, NachoRaik commented on src/controllers/visitsController.js
> +  };
Me parece mucha logica para tenerla toda en el controller. Veria de pasarlo a un service.

2020-11-02 16:18 UTC, NachoRaik commented on src/models/handlers/VisitHandler.js
> +  };
Esto quedo del otro handler?

2020-11-03 01:31 UTC, tomasaccini commented on src/models/handlers/VisitHandler.js
> +  };
Nope. Lo agregué aaca porque quería agregar la validación de que el codigo escaneado sea un código válido de un espacio de la base de datos. Como el '_exit' es algo que no conoce el espacio, es a nivel del QR que generás, no debería tener esa lógica el SpaceHandler, le corresponde al VisitHandler manejar el caso de '_exit' y usar el SpaceHandler cuando tenemos el id real. Tiene sentido?

2020-11-03 02:17 UTC, tomasaccini commented on src/controllers/visitsController.js
> +  };
Done, si te parece que quedó mejor cierro la conver

2020-11-03 12:35 UTC, olifer97 approved these changes
Muy bueno tomi!!

2020-11-03 12:35 UTC, olifer97 commented on test/integration/app.int.test.js
> +        };
un usuario podria escanear un qr varias veces ? y registrar muchas visitas,no? o deberiamos restringirlo en la app ponele.

2020-11-03 13:49 UTC, tomasaccini commented on test/integration/app.int.test.js
> +        };
Desde el lado del server no vamos a poder identificar si son el mismo usuario o diferentes, asique si queremos agregar esa validación la tendríamos que hacer en la app. Igualmente no me parece mal dejar que escanee muchas veces como para "revalidar" que sigue en el local. Nos ayudaría a limpiar un poco la base no recibir tantas visitas, pero no se si es super prioritario, capaz lo agregaría como un issue en el backlog para discutirlo

2020-11-03 13:53 UTC, olifer97 commented on test/integration/app.int.test.js
> +        };
Sisi era como comentario para pensar mas adelante. Es verdad que tendria que si o si ir en la app. O lo q podemos hacer es quedarnos siempre con el escaneo mas nuevo y mas viejo. Pero para agregar mas adelante

2020-11-06 00:51 UTC, NachoRaik approved these changes
Al toke PRro. 
2 cambios boludos nomas, si coincidis y si hay ganas.

2020-11-06 00:51 UTC, NachoRaik commented on src/services/visitRegistration.js
> +module.exports = function visitRegister(visitHandler) {
Lo renombraria a `visitsService` para matchear con lo que tenemos en otros repos.

2020-11-06 00:51 UTC, NachoRaik commented on src/controllers/visitsController.js
> +  const visitRegistration = require('../services/visitRegistration');
Se puede poner afuera del `exports`?

2020-11-06 01:39 UTC, merged